import json


def build_rename_prompt(state: dict) -> str:
    variable_inventory = json.dumps(state.get("variables", []), indent=2)

    return f"""You are an expert reverse engineer.
Rename the function and only the unclear variables in this Ghidra decompiled C code.
Return concrete suggestions that are useful in a reverse-engineering workflow.

Return data matching this structure exactly:
- function_rename: object with target_id, kind, old_name, new_name, explanation
- variable_renames: array of objects with target_id, kind, old_name, new_name, explanation
- summary: string

Rules:
- Never return null or empty strings.
- function_rename.target_id must be "function".
- function_rename.kind must be "function".
- function_rename.old_name must equal the current function name.
- Every explanation must be specific.
- variable_renames should only include variables you are confident about.
- Every variable_renames entry must reuse a target_id and kind from the provided variable inventory.
- Only rename variables whose current names are autogenerated, unclear, overly generic, or misleading.
- If a variable name is already clear, omit it from variable_renames.
- summary should be a short high-value explanation of the function's role.

Return ONLY one valid JSON object.
Do NOT include markdown, code fences, reasoning, or <think> tags.

Current function name: {state["function_name"]}

Variable inventory:
{variable_inventory}

Decompiled code:
{state["decompiled_code"]}
"""