name=AI Ghidra-Plug-in-Explainable-Decompiler
description=Decompiler-style window with AI Rename and Memory Safety Analysis via LangGraph
author=Precision Logic Team. https://github.com/{sezoom, auriza, humaidq, lmsmbzuai}
version=12.0.4
plugin-class=ai.explainable.plugin.AIExplainablePlugin
snapshot.dir=/Users/loic.martins/Documents/Projects/courses/CS8201/cs8201_project
