name=AI Ghidra-Plug-in-Explainable-Decompiler
description=Decompiler-style window with AI Rename and Memory Safety Analysis via LangGraph
author=Precision Logic Team. https://github.com/{sezoom, auriza, humaidq, lmsmbzuai}
version=11.2
plugin-class=ai.renamer.AIRenamerPlugin