import json
import os

from dotenv import load_dotenv
from langchain_core.messages import HumanMessage
from langchain_openai import ChatOpenAI
from langgraph.graph import END, START, StateGraph
from pydantic import BaseModel, Field

from schemas import MemorySafetyAnalysis, RenameSuggestion
from llm import make_llm, extract_k2_think_answer, simple_k2_extract

load_dotenv()

# llm = ChatOpenAI(
#     model="gpt-4o-mini", temperature=0, api_key=os.getenv("OPENAI_API_KEY")
# )

llm = make_llm(os.getenv("LLM1"), 0.1)

# k2-think doesn't support structured output, so we will implement manual parsing
if os.getenv("LLM1") == "k2-think":
    rename_structured = llm
    safety_structured = llm

else:
    rename_structured = llm.with_structured_output(RenameSuggestion)
    safety_structured = llm.with_structured_output(MemorySafetyAnalysis)


class State(BaseModel):
    decompiled_code: str
    function_name: str
    task: str
    variables: list[dict] = Field(default_factory=list)
    result: dict | None = None


def try_rename(prompt):
    global rename_structured
    suggestion = rename_structured.invoke([HumanMessage(content=prompt)])
    return suggestion


def try_securitycheck(prompt):
    global safety_structured
    safety = safety_structured.invoke([HumanMessage(content=prompt)])
    return safety


# general function to retry prompt if the result not parsed correctly
def call_with_retry(fn, prompt, retries=3):
    for i in range(retries):
        try:
            return fn(prompt)
        except Exception as e:
            if i == retries - 1:
                raise


def analyze_node(state: State) -> dict:
    if state.task == "rename":
        variable_inventory = json.dumps(state.variables, indent=2)
        if os.getenv("LLM1") == "k2-think":

            prompt = f"""You are an expert reverse engineer.
            Rename the function and only the unclear variables in this Ghidra decompiled C code.
            Return concrete suggestions that are useful in a reverse-engineering workflow.

            Return data matching this structure exactly:
            - function_rename: object with target_id, kind, old_name, new_name, explanation
            - variable_renames: array of objects with target_id, kind, old_name, new_name, explanation
            - summary: string

            Rules:
            - Never return null or empty strings.
            - function_rename.target_id must be "function".
            - function_rename.kind must be "function".
            - function_rename.old_name must equal the current function name.
            - function_rename.new_name must be a specific descriptive identifier.
            - Every explanation must be specific to that rename, not generic filler.
            - variable_renames should only include variables you are confident about.
            - Every variable_renames entry must reuse a target_id and kind from the provided variable inventory.
            - Only rename variables whose current names are autogenerated, unclear, overly generic, or misleading in context.
            - If a variable name is already clear, descriptive, and appropriate, omit it from variable_renames.
            - Use is_auto_name as a strong hint, but still judge clarity from the code context.
            - Do not polish already-good names just to make them longer.
            - If a name should stay unchanged, omit it from variable_renames. For the function, keep new_name equal to old_name only if no better name is justified.
            - summary should be a short high-value explanation of the function's role.

Return ONLY valid JSON. No explanations, no text outside JSON.

Format:
{{
  "function_rename": {{
    "target_id": "...",
    "kind": "...",
    "old_name": "...",
    "new_name": "...",
    "explanation": "..."
  }},
  "variable_renames": [...],
  "summary": "..."
}}

If you cannot comply, return an empty JSON object: {{}}.

            Current function name: {state.function_name}

            Variable inventory:
            {variable_inventory}

            Decompiled code:
            {state.decompiled_code}
            
            
            """
        else:
            ## prompt for other models not k2-think that support structured output
            prompt = f"""You are an expert reverse engineer.
    Rename the function and only the unclear variables in this Ghidra decompiled C code.
    Return concrete suggestions that are useful in a reverse-engineering workflow.

    Return data matching this structure exactly:
    - function_rename: object with target_id, kind, old_name, new_name, explanation
    - variable_renames: array of objects with target_id, kind, old_name, new_name, explanation
    - summary: string

    Rules:
    - Never return null or empty strings.
    - function_rename.target_id must be "function".
    - function_rename.kind must be "function".
    - function_rename.old_name must equal the current function name.
    - function_rename.new_name must be a specific descriptive identifier.
    - Every explanation must be specific to that rename, not generic filler.
    - variable_renames should only include variables you are confident about.
    - Every variable_renames entry must reuse a target_id and kind from the provided variable inventory.
    - Only rename variables whose current names are autogenerated, unclear, overly generic, or misleading in context.
    - If a variable name is already clear, descriptive, and appropriate, omit it from variable_renames.
    - Use is_auto_name as a strong hint, but still judge clarity from the code context.
    - Do not polish already-good names just to make them longer.
    - If a name should stay unchanged, omit it from variable_renames. For the function, keep new_name equal to old_name only if no better name is justified.
    - summary should be a short high-value explanation of the function's role.

    Current function name: {state.function_name}

    Variable inventory:
    {variable_inventory}

    Decompiled code:
    {state.decompiled_code}
    """
        if os.getenv("LLM1") == "k2-think":
            suggestion = call_with_retry(fn=try_rename, prompt=prompt, retries=3)
            text = suggestion.content
            cleaned = simple_k2_extract(text)

            if not cleaned:
                raise ValueError("LLM returned empty response")
            try:
                parsed = json.loads(cleaned)
            except json.JSONDecodeError:
                raise ValueError(f"Invalid JSON from LLM:\n{cleaned[:500]}")

            return {"result": parsed}
        else:
            suggestion = rename_structured.invoke([HumanMessage(content=prompt)])
            return {"result": suggestion.model_dump()}

    elif state.task == "memory_safety":

        if os.getenv("LLM1") == "k2-think":
            prompt = f"""
            You are an expert in C memory safety and reverse engineering.

            Analyze the following Ghidra decompiled C code for memory safety risks:
            - buffer overflows
            - unsafe pointer usage
            - null pointer dereferences
            - use-after-free
            - unsafe string or formatting functions
            - integer overflows in allocations
            - any other classic memory safety issues

            Return ONLY one valid JSON object.
            Do NOT include markdown.
            Do NOT include code fences.
            Do NOT include reasoning.
            Do NOT include analysis text before or after the JSON.
            Do NOT include <think> tags.
            Do NOT include any extra fields.
            Output must begin with {{ and end with }}.

            The JSON must match exactly this structure:

            {{
              "issues": [
                {{
                  "issue_type": "string",
                  "description": "string",
                  "location": "string",
                  "severity": "high",
                  "suggestion": "string"
                }}
              ],
              "overall_assessment": "string"
            }}

            Rules:
            1. Return exactly one JSON object.
            2. Top-level keys must be exactly:
               - "issues"
               - "overall_assessment"
            3. "issues" must always be present, even if empty.
            4. Every issue object must contain exactly:
               - "issue_type"
               - "description"
               - "location"
               - "severity"
               - "suggestion"
            5. "severity" must be one of: "high", "medium", "low"
            6. If there are no issues, return:
               {{
                 "issues": [],
                 "overall_assessment": "No clear memory safety issues detected."
               }}

            Current function name: {state.function_name}

            Decompiled code:
            {state.decompiled_code}
            """
        else:
            prompt = f"""You are an expert in C memory safety and reverse engineering.
            Analyze the following Ghidra decompiled C code for memory safety risks:
            - buffer overflows (stack/heap)
            - unsafe pointer usage / arithmetic
            - null pointer dereferences
            - use-after-free
            - unsafe string functions
            - integer overflows in allocations
            - any other classic memory safety issues

            Return JSON matching the schema exactly. If no issues, return an empty issues list.

            Decompiled code:
            {state.decompiled_code}
            Current function: {state.function_name}
            """

        if os.getenv("LLM1") == "k2-think":
            analysis = call_with_retry(fn=try_securitycheck, prompt=prompt, retries=3)
            text = analysis.content
            # cleaned = extract_k2_think_answer(text)
            cleaned = simple_k2_extract(text)
            if not cleaned:
                raise ValueError("Empty LLM response")
            try:
                parsed = json.loads(cleaned)
            except json.JSONDecodeError:
                raise ValueError(f"Invalid JSON from LLM:\n{cleaned[:500]}")

            return {"result": parsed}
        else:
            analysis = safety_structured.invoke([HumanMessage(content=prompt)])
            return {"result": analysis.model_dump()}

    raise ValueError(f"Unknown task: {state.task}")


graph = StateGraph(State)
graph.add_node("analyze", analyze_node)
graph.add_edge(START, "analyze")
graph.add_edge("analyze", END)

langgraph_app = graph.compile()
