import json
import os
import time

from dotenv import load_dotenv
from langchain_core.messages import HumanMessage
from langgraph.graph import END, START, StateGraph
from pydantic import BaseModel, Field, ValidationError

from schemas import MemorySafetyAnalysis, RenameSuggestion
from llm import make_llm, simple_k2_extract

load_dotenv()

LLM_NAME = os.getenv("LLM1", "").strip().lower()
IS_K2 = LLM_NAME == "k2-think"

llm = make_llm(os.getenv("LLM1"), 0.1)

# K2-Think does not reliably support structured output, so use raw prompting there.
if IS_K2:
    rename_structured = llm
    safety_structured = llm
else:
    rename_structured = llm.with_structured_output(RenameSuggestion)
    safety_structured = llm.with_structured_output(MemorySafetyAnalysis)


class State(BaseModel):
    decompiled_code: str
    function_name: str
    task: str
    variables: list[dict] = Field(default_factory=list)
    result: dict | None = None


def build_rename_prompt(state: State) -> str:
    variable_inventory = json.dumps(state.variables, indent=2)

    return f"""You are an expert reverse engineer.
Rename the function and only the unclear variables in this Ghidra decompiled C code.
Return concrete suggestions that are useful in a reverse-engineering workflow.

Return data matching this structure exactly:
- function_rename: object with target_id, kind, old_name, new_name, explanation
- variable_renames: array of objects with target_id, kind, old_name, new_name, explanation
- summary: string

Rules:
- Never return null or empty strings.
- function_rename.target_id must be "function".
- function_rename.kind must be "function".
- function_rename.old_name must equal the current function name.
- function_rename.new_name must be a specific descriptive identifier.
- Every explanation must be specific to that rename, not generic filler.
- variable_renames should only include variables you are confident about.
- Every variable_renames entry must reuse a target_id and kind from the provided variable inventory.
- Only rename variables whose current names are autogenerated, unclear, overly generic, or misleading in context.
- If a variable name is already clear, descriptive, and appropriate, omit it from variable_renames.
- Use is_auto_name as a strong hint, but still judge clarity from the code context.
- Do not polish already-good names just to make them longer.
- If a name should stay unchanged, omit it from variable_renames. For the function, keep new_name equal to old_name only if no better name is justified.
- summary should be a short high-value explanation of the function's role.

Return ONLY one valid JSON object.
Do NOT include markdown.
Do NOT include code fences.
Do NOT include reasoning.
Do NOT include analysis text before or after the JSON.
Do NOT include <think> tags.
Do NOT include any extra fields.
Output must begin with {{ and end with }}.

Format:
{{
  "function_rename": {{
    "target_id": "function",
    "kind": "function",
    "old_name": "{state.function_name}",
    "new_name": "string",
    "explanation": "string"
  }},
  "variable_renames": [
    {{
      "target_id": "string",
      "kind": "string",
      "old_name": "string",
      "new_name": "string",
      "explanation": "string"
    }}
  ],
  "summary": "string"
}}

If you cannot comply, return an empty JSON object: {{}}.

Current function name: {state.function_name}

Variable inventory:
{variable_inventory}

Decompiled code:
{state.decompiled_code}
"""


def build_memory_safety_prompt(state: State) -> str:
    return f"""You are an expert in C memory safety and reverse engineering.

Analyze the following Ghidra decompiled C code for memory safety risks:
- buffer overflows
- unsafe pointer usage
- null pointer dereferences
- use-after-free
- unsafe string or formatting functions
- integer overflows in allocations
- any other classic memory safety issues

Return ONLY one valid JSON object.
Do NOT include markdown.
Do NOT include code fences.
Do NOT include reasoning.
Do NOT include analysis text before or after the JSON.
Do NOT include <think> tags.
Do NOT include any extra fields.
Output must begin with {{ and end with }}.

The JSON must match exactly this structure:

{{
  "issues": [
    {{
      "issue_type": "string",
      "description": "string",
      "location": "string",
      "severity": "high",
      "suggestion": "string"
    }}
  ],
  "overall_assessment": "string"
}}

Rules:
1. Return exactly one JSON object.
2. Top-level keys must be exactly:
   - "issues"
   - "overall_assessment"
3. "issues" must always be present, even if empty.
4. Every issue object must contain exactly:
   - "issue_type"
   - "description"
   - "location"
   - "severity"
   - "suggestion"
5. "severity" must be one of: "high", "medium", "low"
6. If there are no issues, return:
   {{
     "issues": [],
     "overall_assessment": "No clear memory safety issues detected."
   }}

Current function name: {state.function_name}

Decompiled code:
{state.decompiled_code}
"""


def build_retry_suffix(schema_name: str, attempt_num: int) -> str:
    return f"""

Your previous response was invalid on attempt {attempt_num}.
Fix it now.

Requirements:
- Return ONLY valid JSON.
- No prose.
- No reasoning.
- No markdown.
- No code fences.
- No <think> tags.
- No text before or after the JSON.
- The JSON must match the {schema_name} schema exactly.
"""


def invoke_k2_and_parse(prompt: str, schema_model, llm_runner, retries: int = 3, delay: float = 1.0) -> dict:
    last_error = None

    for attempt in range(retries):
        current_prompt = prompt
        if attempt > 0:
            current_prompt += build_retry_suffix(schema_model.__name__, attempt + 1)

        try:
            response = llm_runner.invoke([HumanMessage(content=current_prompt)])
            text = response.content if hasattr(response, "content") else str(response)

            cleaned = simple_k2_extract(text)
            if not cleaned or not cleaned.strip():
                raise ValueError("LLM returned empty response")

            parsed = json.loads(cleaned)
            validated = schema_model.model_validate(parsed)
            return validated.model_dump()

        except (json.JSONDecodeError, ValidationError, ValueError) as e:
            last_error = e
            if attempt == retries - 1:
                raw_preview = ""
                try:
                    raw_preview = cleaned[:1000]  # type: ignore[name-defined]
                except Exception:
                    pass
                raise ValueError(
                    f"Failed after {retries} attempts. Last error: {e}\n"
                    f"Last extracted content preview:\n{raw_preview}"
                ) from e

            time.sleep(delay * (attempt + 1))

    raise ValueError(f"Unreachable retry state. Last error: {last_error}")


def analyze_node(state: State) -> dict:
    if state.task == "rename":
        prompt = build_rename_prompt(state)

        if IS_K2:
            result = invoke_k2_and_parse(
                prompt=prompt,
                schema_model=RenameSuggestion,
                llm_runner=rename_structured,
                retries=3,
                delay=1.0,
            )
            return {"result": result}

        suggestion = rename_structured.invoke([HumanMessage(content=prompt)])
        return {"result": suggestion.model_dump()}

    if state.task == "memory_safety":
        prompt = build_memory_safety_prompt(state)

        if IS_K2:
            result = invoke_k2_and_parse(
                prompt=prompt,
                schema_model=MemorySafetyAnalysis,
                llm_runner=safety_structured,
                retries=3,
                delay=1.0,
            )
            return {"result": result}

        analysis = safety_structured.invoke([HumanMessage(content=prompt)])
        return {"result": analysis.model_dump()}

    raise ValueError(f"Unknown task: {state.task}")


graph = StateGraph(State)
graph.add_node("analyze", analyze_node)
graph.add_edge(START, "analyze")
graph.add_edge("analyze", END)

langgraph_app = graph.compile()
